name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.akm47 }} -p ${{ secrets.Physics@13 }}
      - run: docker build -t akm47/Docker-React -f Dockerfile.dev .
      - run: docker run -e CI=true akm47/Docker-React npm test
